blank_issues_enabled: true
contact_links:
  - name: Bug Report
    url: https://github.com/lettercms/lettercms/issues
    about: Report a bug
  - name: Feature Request
    url: https://github.com/lettercms/lettercms/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Ask a Question
    url: https://github.com/lettercms/lettercms/discussions/new?category=help
    about: Ask the community for help
